# Generated by Django 2.1 on 2018-08-13 07:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='')),
                ('url', models.CharField(max_length=255)),
                ('caption', models.CharField(max_length=255)),
                ('description', models.TextField(verbose_name='description')),
                ('category', models.CharField(choices=[('PEOPLE', 'People'), ('NATURE', 'Nature'), ('CITYLIFE', 'City Life'), ('LOVE', 'Love'), ('SPORTS', 'Sports'), ('FAMILY', 'Family')], max_length=100)),
                ('datecreated', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='votes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField()),
                ('status', models.CharField(choices=[('UPVOTE', 1), ('DOWNVOTE', 2)], max_length=100)),
                ('picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photogame.Picture')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
